---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: node1
    driver:
      network:
        - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[chef-apt-docker::default]
      - recipe[jmccann-docker-host::default]
      - recipe[consul-docker::default]
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      consul:
        config:
          consul_local_config:
            bootstrap_expect: 2
            disable_update_check: true
            retry_join:
              - 192.168.33.12
            server: true
          consul_bind_interface: enp0s8
          consul_http_addr: 0.0.0.0
      jmccann-docker-host:
        docker:
          service:
            storage_driver: overlayfs

  - name: node2
    driver:
      network:
        - ["private_network", {ip: "192.168.33.12"}]
    run_list:
      - recipe[chef-apt-docker::default]
      - recipe[jmccann-docker-host::default]
      - recipe[consul-docker::default]
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      consul:
        config:
          consul_local_config:
            bootstrap_expect: 2
            disable_update_check: true
            retry_join:
              - 192.168.33.11
            server: true
          consul_bind_interface: enp0s8
          consul_http_addr: 0.0.0.0
      jmccann-docker-host:
        docker:
          service:
            storage_driver: overlayfs
