---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: node1
    driver:
      network:
        - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[chef-apt-docker::default]
      - recipe[test::certs]
      - recipe[jmccann-docker-host::default]
      - recipe[consul-docker::default]
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      consul-docker:
        config:
          consul_local_config:
            acl_datacenter: dc1
            acl_default_policy: allow
            acl_master_token: 8fa14cdd754f91cc6554c9e71929cce7
            bootstrap_expect: 2
            ca_file: /consul/ssl/ca.crt
            cert_file: /consul/ssl/consul.crt
            datacenter: dc1
            disable_update_check: true
            key_file: /consul/ssl/consul.key
            ports:
              https: 9000
            retry_join:
              - 192.168.33.12
            server: true
            verify_incoming_rpc: true
            verify_outgoing: true
          consul_bind_interface: enp0s8
          consul_http_addr: 0.0.0.0
        volumes:
          - /root/ssl:/consul/ssl
          - /root/entrypoint.sh:/root/entrypoint.sh

  - name: node2
    driver:
      network:
        - ["private_network", {ip: "192.168.33.12"}]
    run_list:
      - recipe[chef-apt-docker::default]
      - recipe[test::certs]
      - recipe[jmccann-docker-host::default]
      - recipe[consul-docker::default]
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      consul-docker:
        config:
          consul_local_config:
            acl_datacenter: dc1
            acl_default_policy: allow
            acl_master_token: 8fa14cdd754f91cc6554c9e71929cce7
            bootstrap_expect: 2
            ca_file: /consul/ssl/ca.crt
            cert_file: /consul/ssl/consul.crt
            datacenter: dc1
            disable_update_check: true
            key_file: /consul/ssl/consul.key
            ports:
              https: 9000
            retry_join:
              - 192.168.33.11
            server: true
            verify_incoming_rpc: true
            verify_outgoing: true
          consul_bind_interface: enp0s8
          consul_http_addr: 0.0.0.0
          entrypoint: /root/entrypoint.sh
        volumes:
          - /root/ssl:/consul/ssl
          - /root/entrypoint.sh:/root/entrypoint.sh
